live:
  url:
    preview: http://localhost/preivew
    start: http://localhost/start
    stop: http://localhost/stop
  whitelist:
    10.1.1.1
    10.1.1.2
    10.1.1.3
  timeout:
    preview: 2
    start: 3
    stop: 1
  host:
    ip: 10.1.2.1
    port: 8080
app:
  datasource:
    readDataSourceSize: 2
    write:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test-master?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    read01:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test-slave01?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    read02:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test-slave02?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/com/damon4u/demo/dao/*.xml
  type-aliases-package: com.damon4u.demo.domain

